# Site settings
url: "https://brunogasparetto.github.io" # the base hostname & protocol for your site, e.g. https://USERNAME.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Change to your lang - This doesn't translate the theme, it just defines the main language the content is written in.
lang: pt-BR

timezone: America/Campo_Grande # Change to your timezone - https://kevinnovak.github.io/Time-Zone-Picker/

title: Bruno Gasparetto
tagline: Dicas de Desenvolvimento
description: Um blog sobre tecnologia, programação, desenvolvimento e gestão. Focado em PHP, JS, Docker e Fluig.
avatar: "assets/img/avatar/avatar.jpg" # The avatar on sidebar

# Social profiles
email: brunogasparetto@gmail.com
github: brunogasparetto
linkedin: brunogasparetto
instagram: brunoguntz
youtube: brunogasparetto

disqus-username: https-brunogasparetto-github-io

# Build settings
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options - https://github.com/jneen/rouge#full-options
    css_class: highlight
    default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-paginate-v2

toc:
  min_level: 2
  max_level: 2

jekyll-minifier:
  exclude: "atom.xml"
  uglifier_args:
    harmony: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      toc: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:title
  - scope:
      path: ""
      type: pages
    values:
      layout: "page"

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json
  - .gitignore
  - .editorconfig

include:
  - _pages

pagination:
  enabled: true
  sort_reverse: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - Página :num'
  trail:
    before: 2
    after: 2
